src/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('register', views.user_register, name='register'),
    path('account/toggle_follow/<user_name>', views.toggle_follow, name='toggle_follow'),
    path('edit_info', views.user_edit_info, name='edit_info'),
    path('edit_profile', views.user_edit_profile, name='edit_profile'),
    path('change_password', views.user_change_password, name='change_password'),
    path('reset_password', views.user_reset_password, name='reset_password'),
    path('profile/<user_name>', views.user_profile, name='profile'),
]

src/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('home', views.home, name='home'),
    path('', views.post_list, name='posts_list'),
    path('posts/tag/<tag_slug>', views.post_list, name='posts_by_tag'),
    path('posts/search/', views.post_search, name='search'),
    path('posts/category/<str:cate>', views.post_list, name='posts_by_category'),
    path('posts/<slug>', views.post_detail, name='post_detail'),
    path('posts/edit/<post_slug>', views.post_edit, name='post_edit'),
    path('posts/create/', views.postCreate, name='add_post'),
    path('posts/draft/', views.post_draft, name='post_draft'),
    path('posts/draft/<post_id>', views.add_to_draft, name='add_to_draft'),
    path('posts/delete/<post_id>', views.delete_post, name='post_delete'),
    path('posts/publish/<post_id>', views.post_publish, name='post_publish'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('delete_comment/<comment_id>', views.delete_comment, name='delete_comment'),
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.shortcuts import reverse
from ckeditor.fields import RichTextField
from django.db.models import Q



def save_image_to(instance, file_name):
    extension = file_name.split('.')[-1]
    return f"blog/{instance.slug}.{extension.lower()}"

#
# class UpComingManager(models.Manager):
#     def get_queryset(self):
#         return super().get_queryset().filter(Q(publish_at__gt=timezone.now()))
#
#
# class DraftManager(models.Manager):
#     def get_queryset(self):
#         return super().get_queryset().filter(Q(publish=True))

#
# class PublishManager(models.Manager):
#     def get_queryset(self):
#         return super().get_queryset().filter(Q(publish=True) & Q(publish_at__lt=timezone.now()))


class PostQueryset(models.QuerySet):
    def upcoming(self):
        return self.filter(Q(publish=True) & Q(publish_at__gt=timezone.now()))


class PostManager(models.Manager):
    def get_queryset(self):
        return PostQueryset(self.model, using=self._db)

    def all_posts(self):
        return self.all()

    def published(self):
        return self.filter(Q(publish=True) & Q(publish_at__lte=timezone.now()))

    # [1] use this or objects.get_queryset().upcoming()
    # def up_coming(self):
    #     return self.filter(Q(publish=True) & Q(publish_at__gt=timezone.now()))
    # [2] use self.queryset().upcoming()
    # def up_coming(self):
    #     return self.get_queryset().upcoming()

    def draft(self):
        return self.filter(publish=False)


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to=save_image_to)
    text = RichTextField()
    publish_at = models.DateTimeField(default=timezone.now())
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique_for_date='created_at', unique=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    tags = models.CharField(max_length=100, default='')
    publish = models.BooleanField(default=True)

    # post manager..
    objects = PostManager()

    class Meta:
        ordering = ['-publish_at']

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=20)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    # name = models.CharField(max_length=25)
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField(blank=True)
    comment = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return f"comment form {self.name} on {self.post}"

src/blog/forms.py
from django import forms
from .models import Comment, Post
from django.utils import timezone


class CustomDateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title', 'text', 'image', 'publish_at', 'category', 'tags', 'publish'
        ]
        widgets = {
            'publish_at': CustomDateTimeInput(attrs={'class': 'timepicker'}),
        }


class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title', 'text', 'image', 'category', 'tags', 'publish'
        ]


class ContactForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField(max_length=50)
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

src/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Post, Comment
from django.core.paginator import Paginator
from .forms import ContactForm, CommentForm, PostForm, PostEditForm
from django.core.mail import send_mail
from django.contrib import messages
from django.conf import settings
from django.db.models import Q
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required

import difflib
from functools import reduce
import operator


def home(request):
    return render(request, 'blog/home.html', {})


@login_required(login_url='account:login')
def postCreate(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.slug = slugify(post.title)
            post.save()
            return redirect('blog:posts_list')
    return render(request, 'blog/post_form.html', {'form': form})


@login_required(login_url='account:login')
def post_edit(request, post_slug):
    # post = Post.objects.published().get(slug=post_slug)
    post = Post.objects.get(slug=post_slug)
    print(post)
    form = PostEditForm(instance=post)
    if request.method == 'POST':
        form = PostEditForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Post edited successfully')
            return redirect('blog:post_detail', slug=post_slug)
    return render(request, 'blog/edit_post.html', {'form': form, 'post': post})


@login_required(login_url='account:login')
def post_list(request, tag_slug=None, cate=None):
    my_following = request.user.profile.following.all()
    print(my_following)
    posts = Post.objects.published().filter(Q(author__in=my_following) | Q(author=request.user))

    if tag_slug:
        posts = Post.objects.published().filter(tags__contains=tag_slug)

    if cate:
        posts = Post.objects.published().filter(category__title=cate)

    # if search:
    #     query = request.GET.get('q')
    #     posts = Post.objects.published().filter(title__icontains=query)

    # posts counter
    posts_count = posts

    # upcoming posts
    upcoming_posts = Post.objects.get_queryset().upcoming()

    # draft
    draft_posts = Post.objects.draft()

    # categories
    categories = Category.objects.all()
    cate_num = {}
    for category in categories:
        cate_num[category] = category.post_set.filter(publish=True).count()

    latest_posts = Post.objects.published().order_by('-publish_at')[:2]
    paginator = Paginator(posts, 8)
    page = request.GET.get('page')
    page_obj = paginator.get_page(page)

    # form
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            name = cd['name']
            email = cd['email']
            message = cd['message']
            send_mail(f"message form blog app, user: {name}", message, 'coloncodes@gmail.com', [email, ])
            messages.success(request, 'successfully sent!')
            return redirect('blog:posts_list')
    else:
        form = ContactForm()

    context = {'posts': page_obj, 'categories': categories,
               'latest_posts': latest_posts, 'upcoming_posts': upcoming_posts,
               'form': form, 'tag_slug': tag_slug, 'cate': cate,
               'posts_count': posts_count, 'cate_num': cate_num, 'query': request.GET.get('q')}

    return render(request, 'blog/index.html', context)


@login_required(login_url='account:login')
def post_search(request):
    empty = True
    query = request.GET.get('q')
    words = []
    for post in Post.objects.published():
        words += post.title.split()
        words += post.text.split()
        words += post.tags.split('-')
        words += post.category.title
    # print(words)
    search_query = [q for q in difflib.get_close_matches(query, words, cutoff=0.6, n=1)]
    print(search_query)
    posts = Post.objects.none()
    test_posts = Post.objects.filter(Q(title__icontains=query) | Q(text__icontains=query))
    if test_posts.count() > 0:
        posts = test_posts
    else:
        for q in search_query:
            posts = Post.objects.published().filter(Q(title__icontains=q) | Q(text__icontains=q) |
                                                    Q(category__title__icontains=q) | Q(tags__icontains=q) |
                                                    Q(title__icontains=query) | Q(text__icontains=query))
        empty = False
    return render(request, 'blog/search.html', {'posts': posts, 'empty': empty, 'search_query': search_query})


@login_required(login_url='account:login')
def post_draft(request):
    posts = Post.objects.draft().filter(author=request.user)
    return render(request, 'blog/post_draft_list.html', {'posts': posts})


@login_required(login_url='account:login')
def add_to_draft(request, post_id):
    post = Post.objects.published().get(id=post_id)
    post.publish = False
    post.save()
    messages.success(request, f'{post} | Added To Draft Posts Successfully!')
    return redirect('blog:post_draft')


@login_required(login_url='account:login')
def delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    messages.success(request, 'deleted successfully!')
    return redirect('blog:posts_list')


@login_required(login_url='account:login')
def post_publish(request, post_id):
    post = Post.objects.draft().get(id=post_id)
    post.publish = True
    post.save()
    messages.success(request, 'Published successfully')
    return redirect('blog:posts_list')


@login_required(login_url='account:login')
def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    post_tags = [tag.strip() for tag in post.tags.split('-')]

    # add comment..
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.name = request.user
            comment.email = request.user.email
            comment.save()
            return redirect('blog:post_detail', slug=post.slug)
    else:
        form = CommentForm()

    # related posts
    posts = Post.objects.published().exclude(pk=post.id)
    related_posts = posts.filter(category=post.category)[:2]

    context = {'post': post, 'tags': post_tags, 'form': form, 'comments': comments,
               'related_posts': related_posts, 'now': timezone.now()}
    return render(request, 'blog/post_detail.html', context)


@login_required(login_url='account:login')
def delete_comment(request, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    comment.delete()
    messages.success(request, 'Comment deleted successfully!')
    return redirect('blog:post_detail', slug=comment.post.slug)


@login_required(login_url='account:login')
def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            print('done')
    else:
        form = ContactForm()
    return render(request, 'blog/index.html', {'form': form})


@login_required(login_url='account:login')
def dashboard(request):
    return render(request, 'blog/dashboard.html', {})

src/blog/templates/blog/comment_form.html
{% extends 'base.html' %}

{% block title%}Blog| Delete Post{% endblock %}

{% block body %}

{% endblock body %}

src/blog/templates/blog/dashboard.html
{% extends 'base.html' %}

{% block title %}DashBoard{% endblock %}

{% block body %}
    <div class="container">
        <h2 class="main-title mv-25">DashBoard</h2>
        <hr>
        <h2 class="main-title pv-25">Welcome {{ user.first_name }} {{ user.last_name }}!</h2>
        <a href="{% url 'blog:post_draft' %}">Drafts</a> |
        <a href="{% url 'blog:add_post' %}">Add new post</a>
    </div>
{% endblock %}

src/blog/templates/blog/edit_post.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title%}Blog| Edit {{ post }}{% endblock %}

{% block body %}
    <div class="col-md-6 offset-md-3">
        <h2 class="main-title">Edit Post: <br>{{ post.title }}</h2>
        <hr>
        <form method="post" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media}}
            {% bootstrap_form form layout='inline-block'%}
            {% buttons %}
                <button type="submit" class="btn btn-success">Save</button>
            {% endbuttons %}
        </form>
    </div>

{% endblock body %}

src/blog/templates/blog/home.html
{% extends 'base.html' %}
{% block title %}
   Home Page
{% endblock title %}

<!--------content------------->

{% block body %}
<div class="hero" >
{% if user.username %}
    <div class="hero-content">
       <h1 class="hero-title">Welcome,<br>{{ user.first_name }} {{ user.last_name }}</h1>
       <p class="hero-p pv-15 text-muted">Share your ideas with others!</p>
       <p class="hero-p text-muted"><a href="{% url 'blog:add_post' %}">Add new post </a></p>
    </div>
{% else %}
    <div class="hero-content">
       <h1 class="hero-title">Welcom To Blog App</h1>
       <p class="hero-p pv-15 text-muted">Amazing blog web app powered by Django</p>
       <p class="hero-p text-muted"><a href="{% url 'account:login' %}">Login </a> or <a
               href="{% url 'account:register' %}"> Create New Account</a> to start!</p>
    </div>
{% endif %}
</div>

{% endblock body %}

src/blog/templates/blog/post_delete.html
{% extends 'base.html' %}

{% block title%}Blog| Delete Post{% endblock %}

{% block body %}

{% endblock body %}

src/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load humanize %}
{% block title%}Blog| {{ post }}{% endblock %}


{% block body %}
<!--<div class="container text-center">-->
<!--<div class="col-md-8 offset-md-4">-->
<!--    <h2 style="background-color: #222222">post</h2>-->
<!--    <div class="detail" style="background-color: white;">-->
<!--        <img width="500px" height="500px" src="post.image.url">-->
<!--    </div>-->
<!--</div>-->
<!--</div>-->
<section >
    <div class="container">
        <div>
            <div class="col-md-8 offset-md-2 ">
                <h1 class="mv-25 main-title">{{ post|title }}</h1>
                <div class="post-meta">
                    <span class="category">{{post.category}}</span>
                    <span class="mr-2">{{ post.publish_at|date:"F d, Y | h: i A"}}</span> &bullet;
                    <span class="ml-2"><span class="fa fa-comments"></span> {{ post.comments.count|apnumber|title }} Comment{{comments|pluralize}}</span>
                </div><br>
                <div class="row mb-5">
                        <div class="col-md-12 mb-4 post-detail-img">
                            <img style="max-height: 500px; width: 100%; object-fit: cover;background-size: cover" src="{{ post.image.url }}" alt="Image placeholder" class="img-fluid">
                        </div>
                    </div>

                <div class="post-content-body">
                    {% if post.publish_at > now and not post.author == request.user %}
                        <h1 class="main-title">Coming soon!</h1>
                    {% else %}
                    {{ post.text|safe }}
                    {% endif %}
                </div>
                <div class="pt-5">
                {% if post.author.username == request.user.username %}
                    <p>
                        <a href="{% url 'blog:post_edit' post.slug %}" class="btn btn-link text-primary">Edit</a>
                        <button class="btn btn-link text-warning" data-toggle="modal" data-target="#draftConfirm">Add To Draft</button>
                        <button class="btn btn-link text-danger" data-toggle="modal" data-target="#deleteConfirm">Delete</button>
                    <hr>
                    </p>
                {% endif %}
                    {% if post.publish_at != post.updated %}
                    <h6><b>Last Update:</b> {{ post.updated|date:"F d, Y | h: i A"}}</h6>
                    {% endif %}
                    <p>
                        <b>Category:</b> <a href="{% url 'blog:posts_by_category' post.category %}">
                            {{ post.category}}</a> | <b>Tags:</b> {% for tag in tags %}<a href="{% url 'blog:posts_by_tag' tag %}">#{{tag}} </a>{% endfor %}
                    </p>
                    <p>by: <a href="{% url 'account:profile' post.author.username %}">{{ post.author }}</a></p>

                </div>
                <!-- add to draft draft cinfirm Modal -->
            <div class="modal fade" id="draftConfirm" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header bg-warning">
                    <h5 class="modal-title" id="exampleModalLongTitle" style="color: white;"><b>Warning</b></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true" style="color: white;">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Are you sure you want to add this post to draft<br>
                      <b>{{ post }}</b>

                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">cancel</button>
                    <a href="{% url 'blog:add_to_draft' post.id %}" type="button" class="btn btn-warning">Add To Draft</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- Delete confirm Modal -->
            <div class="modal fade" id="deleteConfirm" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header bg-danger" >
                    <h5 class="modal-title" id="exampleModalLongTitle" style="color: white;"><b>Warning</b></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true" style="color: white;">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Are you sure you want to delete this post<br>
                      <b>{{ post }}</b>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">cancel</button>
                    <a href="{% url 'blog:post_delete' post.id %}" type="button" class="btn btn-danger">Delete</a>
                  </div>
                </div>
              </div>
            </div>
                <div class="pt-5">
                    <h3 style="color: #0d2c62" class="mb-5 main-title"><b>{{ comments.count|apnumber|title }} Comment{{comments|pluralize}}</b></h3>
                    <ul class="comment-list">
                        {% for comment in comments %}
                        <li class="comment">
                            <div class="vcard">
                            <img src="{{ comment.name.profile.image.url }}" alt="Image">
                            </div>
                            <div class="comment-body">
                                <h3><a href="{% url 'account:profile' comment.name %}">{{comment.name}}</a></h3>
                                <div class="meta">{{ comment.created}}</div>
                                <p>{{comment.comment|safe}}</p>
                                {% if comment.name == request.user or request.user.is_superuser %}
                                <p><button data-toggle="modal" data-target="#deleteCommentConfirm" class="btn btn-link text-danger"> delete</button></p>
                                {% endif %}
                            </div>
                            <li><hr></li>
<!--                            <ul class="children">-->
<!--                                <li class="comment">-->
<!--                                <div class="vcard">-->
<!--                                <img src="images/person_1.jpg" alt="Image placeholder">-->
<!--                                </div>-->
<!--                                <div class="comment-body">-->
<!--                                <h3>Jean Doe</h3>-->
<!--                                <div class="meta">January 9, 2018 at 2:21pm</div>-->
<!--                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>-->
<!--                                <p><a href="#" class="reply">Reply</a></p>-->
<!--                                </div>-->
<!--                                -->
<!--                            </li>-->
<!--                            </ul>-->
                        </li>
                            <div class="modal fade" id="deleteCommentConfirm" tabindex="-1" role="dialog" aria-hidden="true">
                              <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                  <div class="modal-header bg-danger" >
                                    <h5 class="modal-title" id="exampleModalLongTitle" style="color: white;"><b>Warning</b></h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true" style="color: white;">&times;</span>
                                    </button>
                                  </div>
                                  <div class="modal-body">
                                    Are you sure you want to delete this comment<br>
                                      <b>{{ comment.comment|safe }}</b>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">cancel</button>
                                    <a href="{% url 'blog:delete_comment' comment_id=comment.id %}" type="button" class="btn btn-danger">Delete</a>
                                  </div>
                                </div>
                              </div>
                            </div>

                        {% endfor %}
                    </ul>
                <div>
                    <h2 class="main-title">Related Posts</h2>
                    <div class="row">
                        {% for related_post in related_posts %}
                        <div class="col-md-6 col-sm-12">
                            <div class="card">
                              <img src="{{ related_post.image.url }}" class="card-img-top profile-post-img" alt="...">
                              <div class="card-body">
                                <h6 class="card-title">{{ related_post.title }}</h6>
                                <a href="{% url 'blog:post_detail' related_post.slug %}">Read More!</a>
                              </div>
                            </div>
                        </div>
<!--                        <div class="col mb-4">-->
<!--                            <div class="card">-->
<!--                              <img src="{{ related_post.image.url }}" class="card-img-top" alt="...">-->
<!--                              <div class="card-body">-->
<!--                                <h5 class="card-title">{{ related_post }}</h5>-->
<!--                                <p class="card-text">{{related_post.text|safe| truncatechars:200}}</p>-->
<!--                              </div>-->
<!--                            </div>-->
<!--                          </div>-->
                        {% endfor %}
                    </div>
                <div class="comment-form-wrap pt-5">
                    <h3 class="mb-5 main-title">Leave a comment</h3>
                    <form class="p-10 bg-light" method="post">
                        {% csrf_token %}
                        {{ form.media}}
                        {% bootstrap_form form %}
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">Add Comment</button>
                        {% endbuttons %}
                    </form>
                </div>
                </div>
                </div>
        </div>
    </div>
</section>
{% endblock body %}

src/blog/templates/blog/post_draft_list.html
{% extends 'base.html' %}

{% block title%}Blog| Delete Post{% endblock %}

{% block body %}

    <div class="container" id="main">
    {% if posts %}
        <h1 class="main-title pv-25">Draft Posts</h1>
        <table class="table table-striped table-bordered">
        <thead style="background-color: #0d2c62; color: white; letter-spacing: 1.2px;">
            <tr id="hid1">
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Last Update</th>
              <th scope="col">Category</th>
              <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr id="hid2 " >
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ post }}</td>
              <td>{{ post.updated }}</td>
              <td>{{ post.category }}</td>
              <td>
                  <a href="{% url 'blog:post_edit' post.slug %}" class="btn btn-link">Edit</a>
                  <button class="btn btn-link" data-toggle="modal" data-target="#deleteConfirm">Delete</button>
                  <button class="btn btn-link" data-toggle="modal" data-target="#publishConfirm">Publish</button>
            </tr>
            <!-- publish cinfirm Modal -->
            <div class="modal fade" id="publishConfirm" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header bg-success">
                    <h5 class="modal-title" id="exampleModalLongTitle" style="color: white;"><b>Confirm</b></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true" style="color: white;">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Are you sure you want to publish this post<br>
                      <b>{{ post }}</b>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">cancel</button>
                    <a href="{% url 'blog:post_publish' post.id %}" type="button" class="btn btn-success">Publish</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- Delete confirm Modal -->
            <div class="modal fade" id="deleteConfirm" tabindex="-1" role="dialog" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header bg-danger" >
                    <h5 class="modal-title" id="exampleModalLongTitle" style="color: white;"><b>Warning</b></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true" style="color: white;">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Are you sure you want to delete this post<br>
                      <b>{{ post }}</b>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">cancel</button>
                    <a href="{% url 'blog:post_delete' post_id=post.id %}" type="button" class="btn btn-danger">Delete</a>
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <div class="hero" >
            <div class="hero-content">
               <h1 class="hero-title">No Draft Posts</h1>
               <p class="hero-p pv-15 text-muted">You can add new post <a href="{% url 'blog:add_post' %}">HERE</a></p>
            </div>
        </div>
    {% endif %}
    </div>
{% endblock body %}

src/blog/templates/blog/post_update_form.html
{% extends 'base.html' %}

{% block title%}Blog| Update Post{% endblock %}

{% block body %}

{% endblock body %}